Repository RohanGodha/Complete_HTML_CSS_Blog_Website-main, pull requests merged in 2022-10, with the labels that each got.

#8 replacing some links with # in index.html
  index.html
Labels: good first issue, hacktoberfest-accepted

#1 added links to anchor tag in navbar
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#4 Updated navbar
  style.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#9 [Modify]: Added CSS in style.css
  style.css
Labels: good first issue, hacktoberfest-accepted

#7 Added Working Links & Button, Aligned images
  src/index.html
  src/user.png
  style.css
Labels: enhancement, hacktoberfest-accepted

#6 Create disha
  disha
Labels: documentation, hacktoberfest-accepted

#3 Section Added: Footer added
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#2 so i added some code in index file and readme file please review it and approve it, please"
  README.md
  assets/feedback.webp
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#10 add styling to post footer tags
  style.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#5 update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted
